# ===== APPLICATION =====
spring.application.name=SPECCS-LMS
server.port=8080

# ===== JPA =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===== LOGGING =====
logging.level.com.speccs=DEBUG
logging.level.org.springframework.security=DEBUG

# ===== ACTUATOR =====
management.endpoints.web.exposure.include=health,info

# ===== LOAD SECRET CONFIG FROM LOCAL FILE =====
spring.config.import=optional:file:./application-local.properties