user=root
password=root
serverpath=jdbc:mysql://localhost/society_new_25-06
driver=com.mysql.jdbc.Driver
maxConnection=5
userForSybase=speccs
passwordForSybase=speccs1
serverPathForSybase=jdbc:sybase:Tds:192.168.100.235:9100/
driverForSybase=com.sybase.jdbc2.jdbc.SybDriver
maxConnectionForSybase=36
